package com.ducnhu.order.entity;

public enum OrderStatus {
    NEW, CANCELLED, PROCESSING, PACKAGED, PICKED, SHIPPING, DELIVERED, RETURNED, RETURN_REQUESTED, PAID, REFUNDED, PENDING_PAYMENT_PAYPAL
}
