server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # lấy cấu hình ngay trong JAR (src/main/resources/config-repo/**.yml)
          search-locations: classpath:/config-repo
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:ducnhu1234}
    database: ${SPRING_REDIS_DATABASE:0}
    timeout: ${SPRING_REDIS_TIMEOUT:60s}
    ssl: ${SPRING_REDIS_SSL:false}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

  security:
    jwt:
      issuer: "eshop-auth"
      secret: "a2VlcC10aGlzLWtleS1wcml2YXRlLWFuZC1hbmQtb25seS1kZXZlbG9wZXItaGF2ZS1wZXJtaXNzaW9uLXRvLWNoYW5nZS1pdC1ub3RpZnktYnktRHVjbmh1YWQ="
      access-ttl-seconds: 36000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,env,info
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
