-- Databases for all microservices
CREATE DATABASE IF NOT EXISTS eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;           -- auth-service
CREATE DATABASE IF NOT EXISTS catalog_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS cart_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS checkout_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;  -- optional
CREATE DATABASE IF NOT EXISTS customer_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS geo_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS order_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS payment_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;   -- optional
CREATE DATABASE IF NOT EXISTS review_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;    -- optional
CREATE DATABASE IF NOT EXISTS settings_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS shipping_eshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
