server:
  port: 9004
spring:
  application:
    name: customer-service
  config:
    # ← Chỉ rõ URL Config Server trong mạng compose
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 20
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: customer-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/customer_eshopdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Bangkok
    username: root
    password: ducnhu1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:ducnhu1234}
    database: ${SPRING_REDIS_DATABASE:0}
    timeout: ${SPRING_REDIS_TIMEOUT:60s}
    ssl: ${SPRING_REDIS_SSL:false}
  security:
    jwt:
      issuer: eshop-auth            # phải khớp với issuer mà AuthService phát hành token
      secret: ${JWT_SECRET:a2VlcC10aGlzLWtleS1wcml2YXRlLWFuZC1hbmQtb25seS1kZXZlbG9wZXItaGF2ZS1wZXJtaXNzaW9uLXRvLWNoYW5nZS1pdC1ub3RpZnktYnktRHVjbmh1YWQ=}
      access-ttl-seconds: 36000

# Security config l?y t? common-service (JWT)
app:
  security:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false
