server:
  port: 9002

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 20
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/catalog_eshopdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Bangkok
    username: root
    password: ducnhu1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: catalog-service
    listener:
      ack-mode: record
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:ducnhu1234}
    database: ${SPRING_REDIS_DATABASE:0}
    timeout: ${SPRING_REDIS_TIMEOUT:60s}
    ssl: ${SPRING_REDIS_SSL:false}
  # ✨ KHÔNG còn phần autoconfigure.exclude
  security:
    jwt:
      issuer: eshop-auth
      secret: ${JWT_SECRET:a2VlcC10aGlzLWtleS1wcml2YXRlLWFuZC1hbmQtb25seS1kZXZlbG9wZXItaGF2ZS1wZXJtaXNzaW9uLXRvLWNoYW5nZS1pdC1ub3RpZnktYnktRHVjbmh1YWQ=}
      access-ttl-seconds: 1800
    whitelist:
      - /actuator/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /api/categories/**
      - /api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

app:
  security:
    enabled: true

minio:
  endpoint: http://minio:9000
  access-key: ${MINIO_ACCESS_KEY:minio}
  secret-key: ${MINIO_SECRET_KEY:minio123456}
  bucket: exports
  region: us-east-1

jobs:
  categoryHierarchy:
    cron: "0 15 3 * * *" # 3h15 hang ngay
  pageWarmup:
    cron: "0 0/10 * * * *" # moi 10p
  aliasIndex:
    cron: "0 45 * * * *" # moi phut thu 45
  ratingBackfill:
    cron: "0 5 * * * *" # moi phut thu 5